spring:
  application:
    name: rest-service
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: root
    jpa:
      generate-ddl: true
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true

server:
  port: 8072

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

instance:
  hostname: localhost
